"""The FSRS-6 memory model, ported from the fsrs-rs crate that Anki embeds

Docs: https://AnswerDotAI.github.io/fastanki/fsrs.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_fsrs.ipynb.

# %% auto #0
__all__ = ['S_MIN', 'S_MAX', 'D_MIN', 'D_MAX', 'FSRS5_DECAY', 'FSRS6_DECAY', 'DEFAULT_PARAMS', 'ItemSt', 'f32', 'clamp',
           'fsrs_params', 'param_decay', 'forgetting_curve', 'next_interval', 'MemSt', 'step', 'next_states',
           'memory_state_from_sm2']

# %% ../nbs/03_fsrs.ipynb #ae880466
import math
from struct import pack, unpack
from collections import namedtuple
from fastcore.utils import *

# %% ../nbs/03_fsrs.ipynb #2404bf38
S_MIN,S_MAX,D_MIN,D_MAX = 0.001,36500.0,1.0,10.0
FSRS5_DECAY,FSRS6_DECAY = 0.5,0.1542

DEFAULT_PARAMS = [0.212,1.2931,2.3065,8.2956,6.4133,0.8334,3.0194,0.001,1.8722,0.1666,0.796,
    1.4835,0.0614,0.2629,1.6483,0.6014,1.8729,0.5425,0.0912,0.0658,FSRS6_DECAY]

_CLAMPS = [(S_MIN,100.)]*4 + [(D_MIN,D_MAX),(0.001,4.0),(0.001,4.0),(0.001,0.75),(0.,4.5),(0.,0.8),(0.001,3.5),
    (0.001,5.0),(0.001,0.25),(0.001,0.9),(0.,4.0),(0.,1.0),(1.0,6.0),(0.,2.0),(0.,2.0),(0.,0.8),(0.1,0.8)]

def f32(x): return unpack('f', pack('f', x))[0]
def clamp(x, lo, hi): return min(max(x,lo),hi)

def fsrs_params(w):
    "Upgrade a 0/17/19/21-length parameter list to FSRS-6's 21 numbers and clip to legal ranges, like `FSRS::new`"
    w = [float(x) for x in w] or list(DEFAULT_PARAMS)
    if len(w)==17:
        w[4],w[5],w[6] = w[4]+2*w[5], math.log(w[5]*3+1)/3, w[6]+0.5
        w += [0.,0.,0.,FSRS5_DECAY]
    elif len(w)==19: w += [0.,FSRS5_DECAY]
    assert len(w)==21, f"invalid FSRS parameter count: {len(w)}"
    return [f32(clamp(x,*b)) for x,b in zip(w,_CLAMPS)]

def param_decay(w):
    "The forgetting-curve decay for a *raw* (pre-upgrade) parameter list, Anki's `get_decay_from_params`"
    return FSRS6_DECAY if not len(w) else (FSRS5_DECAY if len(w)<21 else w[20])

# %% ../nbs/03_fsrs.ipynb #cdaadaa6
def forgetting_curve(w, t, s):
    "Probability of recall `t` days after a review that left stability `s`"
    decay = -w[20]
    factor = math.exp(math.log(0.9)/decay) - 1
    return f32((t/s*factor + 1)**decay)

def next_interval(w, s, dr):
    "The (fractional) days until retrievability falls to desired retention `dr`, at stability `s`"
    decay = -w[20]
    factor = math.exp(math.log(0.9)/decay) - 1
    return f32(s/factor*(dr**(1/decay) - 1))

# %% ../nbs/03_fsrs.ipynb #ced935c2
class MemSt(namedtuple('MemSt', 'stability difficulty')):
    "An FSRS memory state: `stability` in days, `difficulty` in 1-10"

def _init_d(w, r): return w[4] - math.exp(w[5]*(r-1)) + 1

def _next_d(w, d, r):
    nd = d + (10-d)*(-w[6]*(r-3))/9
    return clamp(w[7]*(_init_d(w,4)-nd)+nd, D_MIN, D_MAX)

def _s_success(w, s, d, r, rating):
    hp = w[15] if rating==2 else 1.0
    eb = w[16] if rating==4 else 1.0
    return s*(math.exp(w[8])*(11-d)*s**-w[9]*(math.exp((1-r)*w[10])-1)*hp*eb + 1)

def _s_fail(w, s, d, r):
    ns = w[11]*d**-w[12]*((s+1)**w[13]-1)*math.exp((1-r)*w[14])
    return min(ns, s/math.exp(w[17]*w[18]))

def _s_short_term(w, s, rating):
    "Same-day stability. Floors the multiplier at 1 for Good/Easy only"
    sinc = math.exp(w[17]*(rating-3+w[18]))*s**-w[19]
    return s*(max(sinc, 1.0) if rating>=3 else sinc)

def step(w, delta_t, rating, mem):
    "Memory state after rating a card `delta_t` days since its last review (`mem` None: first rating of a new card)"
    if mem is None:
        r = clamp(rating, 1, 4)
        return MemSt(f32(clamp(w[r-1], S_MIN, S_MAX)), f32(clamp(_init_d(w,r), D_MIN, D_MAX)))
    s,d = clamp(mem.stability, S_MIN, S_MAX), clamp(mem.difficulty, D_MIN, D_MAX)
    r = forgetting_curve(w, delta_t, s)
    if delta_t==0:  ns = _s_short_term(w, s, rating)
    elif rating==1: ns = _s_fail(w, s, d, r)
    else:           ns = _s_success(w, s, d, r, rating)
    return MemSt(f32(clamp(ns, S_MIN, S_MAX)), f32(_next_d(w, d, rating)))

ItemSt = namedtuple('ItemSt', 'mem ivl')

def next_states(w, mem, dr, days_elapsed):
    "For each rating 1-4 (index `[ease-1]`), the next `MemSt` and its desired-retention interval"
    sts = [step(w, float(days_elapsed), rating, mem) for rating in (1,2,3,4)]
    return [ItemSt(m, next_interval(w, m.stability, dr)) for m in sts]

# %% ../nbs/03_fsrs.ipynb #2188716f
def memory_state_from_sm2(w, ease_factor, interval, sm2_retention=0.9):
    "A `MemSt` inferred from SM-2 `ease_factor` (eg 2.5) and `interval` days"
    decay = -w[20]
    factor = 0.9**(1/decay) - 1
    s = max(interval, S_MIN)*factor/(sm2_retention**(1/decay) - 1)
    d = 11 - (ease_factor-1)/(math.exp(w[8])*s**-w[9]*(math.exp((1-sm2_retention)*w[10]) - 1))
    return MemSt(f32(s), f32(clamp(d, D_MIN, D_MAX)))
