"""The v3 scheduler: card states, answer buttons, and the revlog, compatible with every Anki client

Docs: https://AnswerDotAI.github.io/fastanki/scheduler.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_scheduler.ipynb.

# %% auto #0
__all__ = ['DAY', 'EASE_AGAIN', 'EASE_HARD', 'EASE_EASY', 'MIN_EASE', 'RLog', 'NewSt', 'LearnSt', 'ReviewSt', 'RelearnSt',
           'Answers', 'ivl_days', 'ivl_secs', 'step_again_delay', 'step_hard_delay', 'step_good_delay',
           'step_current_delay', 'step_remaining_good', 'fuzz_delta', 'fuzz_bounds', 'with_fuzz', 'fuzz_factor',
           'min_fuzz_ivl', 'learn_fuzz', 'Ctx', 'mk_ctx', 'leech_threshold_met', 'card_state', 'preset_params',
           'allow_short_term', 'ignore_revlogs_before']

# %% ../nbs/04_scheduler.ipynb #c575cdbb
import json, time, random
from datetime import datetime, timezone
from collections import namedtuple
from fastcore.utils import *
from .schema import *
from .collection import *
from ._proto import deck_config_pb2, decks_pb2
from .fsrs import *

# %% ../nbs/04_scheduler.ipynb #682bf3b4
@patch
def deck_conf(self:Collection, did):
    "The parsed `DeckConfig.Config` preset governing deck `did`"
    k = decks_pb2.Deck.KindContainer()
    k.ParseFromString(self.q1('select kind from decks where id=?', did))
    blob = self.q1('select config from deck_config where id=?', k.normal.config_id or 1) or default_deck_config()
    c = deck_config_pb2.DeckConfig.Config()
    c.ParseFromString(blob)
    return c

# %% ../nbs/04_scheduler.ipynb #4fdb2d86
class NewSt(namedtuple('NewSt', 'position')):
    "Not yet studied; `position` orders the new queue"
    def ivl_kind(self):    return 0
    def revlog_kind(self): return 0

class LearnSt(namedtuple('LearnSt', 'remaining secs elapsed mem', defaults=(0,None))):
    "In the learning steps: `remaining` steps left, `secs` until the next showing"
    def ivl_kind(self):    return -self.secs
    def revlog_kind(self): return 0

class ReviewSt(namedtuple('ReviewSt', 'ivl ease lapses elapsed leeched mem', defaults=(0,0,False,None))):
    "Graduated: due again in `ivl` days, growing by `ease`"
    def ivl_kind(self):    return self.ivl
    def revlog_kind(self): return 3 if self.elapsed<self.ivl else 1

class RelearnSt(namedtuple('RelearnSt', 'learn review')):
    "A failed review: `learn` steps to redo, then back to `review`"
    def ivl_kind(self):    return self.learn.ivl_kind()
    def revlog_kind(self): return 2

class Answers(namedtuple('Answers', 'current again hard good easy')):
    "One state per answer button (index by ease 1-4), plus the current state"

def ivl_days(iv, secs_to_rollover):
    "Convert a seconds interval that crosses the day boundary to days (Anki's `maybe_as_days`)"
    if iv<0 and -iv>=secs_to_rollover: return (-iv-secs_to_rollover)//86400 + 1
    return iv

def ivl_secs(iv):
    "An interval in plain seconds"
    return -iv if iv<0 else iv*86400

# %% ../nbs/04_scheduler.ipynb #b7bf1d31
DAY = 86400

def _round(x):
    "Round half away from zero, like Rust's `round` (Python's `round` is banker's)"
    return int(x+0.5) if x>=0 else -int(-x+0.5)

def _step_secs(steps, i): return int(steps[i]*60) if 0<=i<len(steps) else None
def _step_idx(steps, remaining): return clamp(len(steps)-remaining%1000, 0, max(len(steps)-1, 0))
def _round_days(secs): return _round(secs/DAY)*DAY if secs>DAY else secs

def step_again_delay(steps): return _step_secs(steps, 0)

def step_hard_delay(steps, remaining):
    idx = _step_idx(steps, remaining)
    cur = _step_secs(steps, idx) or _step_secs(steps, 0)
    if cur is None: return None
    if idx>0: return cur
    nxt = _step_secs(steps, 1)
    if nxt is not None: return _round_days((cur+nxt)//2)
    return _round_days(min(cur*3//2, cur+DAY))

def step_good_delay(steps, remaining): return _step_secs(steps, _step_idx(steps, remaining)+1)
def step_current_delay(steps, remaining): return _step_secs(steps, _step_idx(steps, remaining)) or 0
def step_remaining_good(steps, remaining): return len(steps)-_step_idx(steps, remaining)-1

# %% ../nbs/04_scheduler.ipynb #701a80dc
_FUZZ_RANGES = [(2.5,7.0,0.15), (7.0,20.0,0.1), (20.0,None,0.05)]

def fuzz_delta(ivl):
    "Days of fuzz applied either side of `ivl`"
    if ivl<2.5: return 0.0
    d = 1.0
    for start,end,f in _FUZZ_RANGES: d += f*max(min(ivl, end or ivl)-start, 0)
    return d

def fuzz_bounds(
    ivl,      # Undisturbed interval in days (may be fractional)
    lo=1,     # Minimum permitted result
    hi=36500, # Maximum permitted result
):
    "Inclusive `(lower, upper)` day bounds for a fuzzed interval, respecting `lo`/`hi`"
    lo = min(lo, hi)
    ivl = clamp(ivl, lo, hi)
    d = fuzz_delta(ivl)
    l,u = _round(ivl-d), _round(ivl+d)
    l,u = clamp(l, lo, hi), clamp(u, lo, hi)
    if u==l and u>2 and u<hi: u = l+1
    return l,u

def with_fuzz(fz, ivl, lo, hi):
    "`ivl` fuzzed by factor `fz` in [0,1) within `lo`/`hi`; None means round and clamp only"
    if fz is None: return clamp(_round(ivl), lo, hi)
    l,u = fuzz_bounds(ivl, lo, hi)
    return int(l + fz*(1+u-l))

def fuzz_factor(cid, reps):
    "Deterministic per-(card, rep) fuzz factor in [0,1)"
    return random.Random(cid+reps).random()

def min_fuzz_ivl(ivl, prev_ivl, max_ivl):
    "Minimum for a fuzzed FSRS review interval: fuzz may not shrink an interval that grew (Anki's `minimum_review_fuzz_interval`)"
    upper = fuzz_bounds(ivl, 1, max_ivl)[1]
    if _round(ivl) > prev_ivl: return prev_ivl+1
    return prev_ivl if prev_ivl <= upper else 0

def learn_fuzz(fz_seed, secs):
    "Intraday learning delay with Anki's up-to-25% (max 5min) extension; `fz_seed` None leaves it alone"
    if fz_seed is None: return secs
    upper = secs + int(min(secs*0.25, 300.0))
    if secs >= upper: return secs
    return random.Random(fz_seed).randrange(secs, upper)

# %% ../nbs/04_scheduler.ipynb #a57d10b3
_CTX = 'fuzz steps relearn_steps grad_good grad_easy init_ease hard_mult easy_mult ivl_mult lapse_mult max_ivl min_lapse_ivl leech_threshold fsrs allow_short short_steps'
class Ctx(namedtuple('Ctx', _CTX, defaults=(None,False,False))):
    "Everything a state transition needs: the deck preset's numbers plus this answer's fuzz factor"

def mk_ctx(cfg, fuzz=None, fsrs=None, **over):
    "A `Ctx` from deck preset `cfg`, overridable by keyword"
    d = dict(fuzz=fuzz, steps=list(cfg.learn_steps), relearn_steps=list(cfg.relearn_steps),
        grad_good=cfg.graduating_interval_good, grad_easy=cfg.graduating_interval_easy, init_ease=cfg.initial_ease,
        hard_mult=cfg.hard_multiplier, easy_mult=cfg.easy_multiplier, ivl_mult=cfg.interval_multiplier,
        lapse_mult=cfg.lapse_multiplier, max_ivl=cfg.maximum_review_interval,
        min_lapse_ivl=cfg.minimum_lapse_interval, leech_threshold=cfg.leech_threshold, fsrs=fsrs)
    d.update(over)
    return Ctx(**d)

def _min_max(ctx, minimum):
    hi = max(ctx.max_ivl, 1)
    return clamp(minimum, 1, hi), hi

def leech_threshold_met(lapses, threshold):
    "True at `threshold` lapses, and every half-threshold (rounded up) after"
    if not threshold: return False
    half = max(-(-threshold//2), 1)
    return lapses>=threshold and (lapses-threshold)%half==0

# %% ../nbs/04_scheduler.ipynb #beff5ce2
EASE_AGAIN,EASE_HARD,EASE_EASY,MIN_EASE = -0.2,-0.15,0.15,1.3

def _constrain_passing(ctx, ivl, minimum, fuzz=True):
    if ctx.fsrs is None: ivl *= ctx.ivl_mult
    lo,hi = _min_max(ctx, minimum)
    return with_fuzz(ctx.fuzz, ivl, lo, hi) if fuzz else clamp(_round(ivl), lo, hi)

def _mem(ctx, rating):
    "The FSRS memory state this rating leads to (None under SM-2)"
    return ctx.fsrs[rating-1].mem if ctx.fsrs is not None else None

@patch
def _passing_ivls(self:ReviewSt, ctx):
    "Hard/good/easy intervals, each at least a day past the one before"
    if ctx.fsrs is not None: return self._passing_fsrs_ivls(ctx)
    if self.elapsed < self.ivl: return self._passing_early_ivls(ctx)
    cur,late = max(self.ivl,1), max(self.elapsed-self.ivl, 0)
    hard_min = 0 if ctx.hard_mult<=1.0 else self.ivl+1
    hard = _constrain_passing(ctx, cur*ctx.hard_mult, hard_min)
    good_min = self.ivl+1 if ctx.hard_mult<=1.0 else hard+1
    good = _constrain_passing(ctx, (cur+late/2)*self.ease, good_min)
    easy = _constrain_passing(ctx, (cur+late)*self.ease*ctx.easy_mult, good+1)
    return hard,good,easy

@patch
def _passing_fsrs_ivls(self:ReviewSt, ctx):
    "FSRS intervals come straight from the memory model; fuzz may not shrink an interval that grew"
    ivls = [s.ivl for s in ctx.fsrs]
    hard = _constrain_passing(ctx, ivls[1], max(min_fuzz_ivl(ivls[1], self.ivl, ctx.max_ivl), 1))
    good = _constrain_passing(ctx, ivls[2], max(min_fuzz_ivl(ivls[2], self.ivl, ctx.max_ivl), hard+1))
    easy = _constrain_passing(ctx, ivls[3], max(min_fuzz_ivl(ivls[3], self.ivl, ctx.max_ivl), good+1))
    return hard,good,easy

@patch
def _passing_early_ivls(self:ReviewSt, ctx):
    "Reviewed before due: elapsed days stand in for scheduled, no fuzz"
    sched,elap = max(self.ivl,1), self.elapsed
    hard = _constrain_passing(ctx, max(elap*ctx.hard_mult, sched*ctx.hard_mult/2), 0, fuzz=False)
    good = _constrain_passing(ctx, max(elap*self.ease, sched), 0, fuzz=False)
    bonus = ctx.easy_mult - (ctx.easy_mult-1.0)/2
    easy = _constrain_passing(ctx, max(elap*self.ease, sched)*bonus, 0, fuzz=False)
    return hard,good,easy

@patch
def _failing_ivl(self:ReviewSt, ctx):
    if ctx.fsrs is not None: return ctx.fsrs[0].ivl   # in FSRS, fuzz applies when leaving relearning
    lo,hi = _min_max(ctx, ctx.min_lapse_ivl)
    return with_fuzz(ctx.fuzz, max(self.ivl,1)*ctx.lapse_mult, lo, hi)

@patch
def next_answers(self:ReviewSt, ctx):
    hard,good,easy = self._passing_ivls(ctx)
    lapses = self.lapses+1
    fail = self._failing_ivl(ctx)
    days = max(_round(max(fail,0)), 1)
    again_review = ReviewSt(days, max(self.ease+EASE_AGAIN, MIN_EASE), lapses, mem=_mem(ctx,1),
        leeched=leech_threshold_met(lapses, ctx.leech_threshold))
    if ctx.relearn_steps:
        again = RelearnSt(LearnSt(len(ctx.relearn_steps), step_again_delay(ctx.relearn_steps), mem=_mem(ctx,1)), again_review)
    elif ctx.fsrs is not None and ctx.allow_short and (ctx.short_steps or not ctx.relearn_steps) and fail < 0.5:
        again = RelearnSt(LearnSt(0, int(fail*86400), mem=_mem(ctx,1)), again_review)
    else: again = again_review
    return Answers(self, again, ReviewSt(hard, max(self.ease+EASE_HARD, MIN_EASE), self.lapses, mem=_mem(ctx,2)),
        ReviewSt(good, self.ease, self.lapses, mem=_mem(ctx,3)),
        ReviewSt(easy, self.ease+EASE_EASY, self.lapses, mem=_mem(ctx,4)))

# %% ../nbs/04_scheduler.ipynb #a7371ea7
def _graduate(ctx, rating):
    "Leave the learning steps for review: `grad_good`/`grad_easy` days under SM-2, the model's interval under FSRS"
    lo,hi = _min_max(ctx, 1)
    if ctx.fsrs is None:
        ivl = ctx.grad_easy if rating==4 else ctx.grad_good
        return ReviewSt(with_fuzz(ctx.fuzz, max(_round(ivl),1), lo, hi), ctx.init_ease)
    st = ctx.fsrs[rating-1]
    if rating==4: lo = with_fuzz(ctx.fuzz, ctx.fsrs[2].ivl, lo, hi) + 1   # Easy must clear the fuzzed Good interval
    return ReviewSt(with_fuzz(ctx.fuzz, max(_round(st.ivl),1), lo, hi), ctx.init_ease, mem=st.mem)

def _learn_short(ctx, rating, steps):
    "The FSRS short-term state when the model wants this answer back the same day, else None"
    if ctx.fsrs is None or not ctx.allow_short or not (ctx.short_steps or not steps): return None
    st = ctx.fsrs[rating-1]
    return st if st.ivl < 0.5 else None

@patch
def next_answers(self:LearnSt, ctx):
    steps = ctx.steps
    def grad_or_short(rating, remaining):
        s = _learn_short(ctx, rating, steps)
        if s is not None: return LearnSt(remaining, int(s.ivl*86400), mem=s.mem)
        return _graduate(ctx, rating)
    ad = step_again_delay(steps)
    again = LearnSt(len(steps), ad, mem=_mem(ctx,1)) if ad is not None else grad_or_short(1, len(steps))
    hd = step_hard_delay(steps, self.remaining)
    hard = LearnSt(self.remaining, hd, mem=_mem(ctx,2)) if hd is not None else grad_or_short(2, self.remaining)
    gd = step_good_delay(steps, self.remaining)
    good = LearnSt(step_remaining_good(steps, self.remaining), gd, mem=_mem(ctx,3)) if gd is not None else grad_or_short(3, self.remaining)
    return Answers(self, again, hard, good, _graduate(ctx, 4))

@patch
def next_answers(self:NewSt, ctx):
    "A new card answers like a learning card that just failed"
    return LearnSt(len(ctx.steps), 0).next_answers(ctx)._replace(current=self)

def _relearn_pass(rl, ctx, rating):
    "A passing FSRS answer in relearning: back to review, or another same-day step if the model wants one"
    lo,hi = _min_max(ctx, 1)
    st = ctx.fsrs[rating-1]
    rev = rl.review._replace(ivl=with_fuzz(ctx.fuzz, max(_round(st.ivl),1), lo, hi), mem=st.mem)
    if ctx.allow_short and (ctx.short_steps or not ctx.relearn_steps) and st.ivl < 0.5:
        rem = rl.learn.remaining if rating==2 else step_remaining_good(ctx.relearn_steps, rl.learn.remaining)
        return RelearnSt(rl.learn._replace(remaining=rem, secs=int(st.ivl*86400), elapsed=0, mem=st.mem), rev)
    return rev

@patch
def next_answers(self:RelearnSt, ctx):
    steps,rev,fs = ctx.relearn_steps, self.review, ctx.fsrs
    fail = rev._failing_ivl(ctx)
    days = max(_round(max(fail,0)), 1)
    ad = step_again_delay(steps)
    if ad is not None: again = RelearnSt(LearnSt(len(steps), ad, mem=_mem(ctx,1)), rev._replace(ivl=days, elapsed=0, mem=_mem(ctx,1)))
    elif fs is not None:
        lo,hi = _min_max(ctx, 1)
        again_rev = rev._replace(ivl=with_fuzz(ctx.fuzz, max(_round(fail),1), lo, hi), mem=fs[0].mem)
        if ctx.allow_short and (ctx.short_steps or not steps) and fail < 0.5:
            again = RelearnSt(LearnSt(len(steps), int(fail*86400), mem=fs[0].mem), again_rev)
        else: again = again_rev
    else: again = rev
    hd = step_hard_delay(steps, self.learn.remaining)
    if hd is not None: hard = RelearnSt(self.learn._replace(secs=hd, elapsed=0, mem=_mem(ctx,2)), rev._replace(elapsed=0, mem=_mem(ctx,2)))
    elif fs is not None: hard = _relearn_pass(self, ctx, 2)
    else: hard = rev
    gd = step_good_delay(steps, self.learn.remaining)
    if gd is not None:
        good = RelearnSt(LearnSt(step_remaining_good(steps, self.learn.remaining), gd, mem=_mem(ctx,3)), rev._replace(elapsed=0, mem=_mem(ctx,3)))
    elif fs is not None: good = _relearn_pass(self, ctx, 3)
    else: good = rev
    if fs is not None:
        lo,hi = _min_max(ctx, 1)
        lo = with_fuzz(ctx.fuzz, fs[2].ivl, lo, hi) + 1
        easy = rev._replace(ivl=with_fuzz(ctx.fuzz, max(_round(fs[3].ivl),1), lo, hi), elapsed=0, mem=fs[3].mem)
    else: easy = rev._replace(ivl=rev.ivl+1, elapsed=0)
    return Answers(self, again, hard, good, easy)

# %% ../nbs/04_scheduler.ipynb #01548bec
def _card_data(c):
    "The card's `data` column as a dict"
    try: return json.loads(c.data) if c.data else {}
    except ValueError: return {}

def card_state(c, cfg, today, now=None):
    "The scheduling state of card row `c` under preset `cfg`"
    now = ifnone(now, int(time.time()))
    left = c.left%1000
    d = _card_data(c)
    mem = MemSt(d['s'], d['d']) if 's' in d and 'd' in d else None
    if c.type==0: return NewSt(max(c.due,0))
    if c.type==2:
        due = min(c.due, today)
        return ReviewSt(c.ivl, c.factor/1000, c.lapses, elapsed=max(c.ivl-(due-today), 0), mem=mem)
    steps = list(cfg.learn_steps if c.type==1 else cfg.relearn_steps)
    last = step_current_delay(steps, left)
    if c.queue==1: elapsed = now - (c.due - learn_fuzz(c.id+c.reps-1 if c.reps else None, last))
    elif c.queue==3: elapsed = (today - c.due + max(last//DAY, 1))*DAY
    else: elapsed = 0
    learn = LearnSt(left, last, elapsed, mem=mem)
    if c.type==1: return learn
    return RelearnSt(learn, ReviewSt(c.ivl, c.factor/1000, c.lapses, elapsed=c.ivl, mem=mem))

# %% ../nbs/04_scheduler.ipynb #290dbd5f
RLog = namedtuple('RLog', 'id ease ivl lastIvl factor type')

@patch
def fsrs_on(self:Collection):
    "Is FSRS enabled for this collection?"
    return bool(self.conf('fsrs', False))

def preset_params(cfg):
    "The preset's raw FSRS parameters: version 6, else 5, else 4.5, else [] meaning the defaults"
    return list(cfg.fsrs_params_6 or cfg.fsrs_params_5 or cfg.fsrs_params_4)

def allow_short_term(raw):
    "May FSRS schedule same-day steps? Requires non-zero short-term params (default params qualify)"
    if not raw: return True
    return raw[17]>0 and raw[18]>0 if len(raw)>=19 else False

def ignore_revlogs_before(cfg):
    "The preset's ignore-revlogs-before date as epoch ms (0 if unset)"
    s = cfg.ignore_revlogs_before_date
    return int(datetime.strptime(s, '%Y-%m-%d').replace(tzinfo=timezone.utc).timestamp()*1000) if s else 0

@patch
def _deck_dr(self:Collection, did, cfg):
    "Effective desired retention: the deck's own override, else the preset's"
    k = decks_pb2.Deck.KindContainer()
    k.ParseFromString(self.q1('select kind from decks where id=?', did))
    return k.normal.desired_retention if k.normal.HasField('desired_retention') else cfg.desired_retention

# %% ../nbs/04_scheduler.ipynb #6546e9b9
def _rl_days(e, next_day_at): return max(next_day_at - e.id//1000, 0)//86400

def _fsrs_reviews(entries, next_day_at, ignore_before=0):
    "Filter a card's revlog rows for FSRS and compute (rating, delta_t) pairs; None if nothing usable"
    first_learn = first_grade = None
    for i in reversed(range(len(entries))):
        e = entries[i]
        if e.type==3 and e.factor==0: continue                                   # cramming
        if e.ease>0 and e.id>ignore_before and (e.ivl>=1 or e.ivl<=-86400): first_grade = i
        if e.ease>0 and e.type==0: first_learn = i
        elif e.type==4 and e.factor==0:                                          # reset
            if first_learn is None and first_grade is None: return None
            break
        elif first_learn is not None: break
    complete = first_learn is not None
    if complete and entries[first_learn].id < ignore_before and first_learn < len(entries)-1:
        complete,first_learn = False,None
    start = first_learn if first_learn is not None else first_grade
    if start is None: return None
    kept = [e for e in entries[start:] if e.ease>0 and not (e.type==3 and e.factor==0)]
    if not kept: return None
    ds = [0] + [_rl_days(a, next_day_at)-_rl_days(b, next_day_at) for a,b in zip(kept, kept[1:])]
    return [(e.ease, dt) for e,dt in zip(kept, ds)], complete, kept

def _memory_from_revlog(w, entries, next_day_at, historical_retention=0.9, ignore_before=0):
    "Replay a card's revlog into a `MemSt`, starting a truncated history from an SM-2 approximation"
    out = _fsrs_reviews(entries, next_day_at, ignore_before)
    if out is None: return None
    revs,complete,kept = out
    mem = None
    if not complete:
        first = kept[0]
        ease = (first.factor or 2500)/1000
        mem = memory_state_from_sm2(w, ease, max(first.ivl, 1), historical_retention)
        if ease <= 1.1: mem = mem._replace(difficulty=f32((ease-0.1)*9 + 1))   # entry was written by FSRS itself
        revs = revs[1:]
    for rating,dt in revs: mem = step(w, dt, rating, mem)
    return mem

# %% ../nbs/04_scheduler.ipynb #18d38eb4
@patch
def _fsrs_ctx(self:Collection, c, cfg, next_day):
    "(four FSRS next-states, desired retention, decay) for card `c`, rebuilding memory from the revlog when absent"
    raw = preset_params(cfg)
    w = fsrs_params(raw)
    d = _card_data(c)
    mem = MemSt(d['s'], d['d']) if 's' in d and 'd' in d else None
    if mem is None and c.type!=0:
        rows = [RLog(*r) for r in self.q('select id, ease, ivl, lastIvl, factor, type from revlog where cid=? order by id', c.id)]
        mem = _memory_from_revlog(w, rows, next_day, cfg.historical_retention, ignore_revlogs_before(cfg))
    lrt = d.get('lrt') or self.q1('select max(id)/1000 from revlog where cid=? and ease between 1 and 4 and (type!=3 or factor!=0)', c.id)
    days = max(next_day-lrt, 0)//86400 if lrt else 0
    dr = self._deck_dr(c.did, cfg)
    return next_states(w, mem, dr, days), dr, param_decay(raw)

# %% ../nbs/04_scheduler.ipynb #fb9dfbdd
@patch
def _card_answers(self:Collection, cid, fuzz, now):
    "Load card `cid` fresh and compute its state, the four answer outcomes, and FSRS extras"
    c = Card(*self.q('select * from cards where id=?', cid)[0])
    assert not c.odid, "cards in filtered decks are not supported"
    now = ifnone(now, int(time.time()))
    today,next_day = self.timing()
    cfg = self.deck_conf(c.did)
    fs = dr = decay = None
    if self.fsrs_on():
        fs,dr,decay = self._fsrs_ctx(c, cfg, next_day)
        raw = preset_params(cfg)
        ctx = mk_ctx(cfg, fuzz=fuzz_factor(c.id, c.reps) if fuzz else None, fsrs=fs, allow_short=allow_short_term(raw),
            short_steps=bool(self.conf('fsrsShortTermWithStepsEnabled', False)))
    else: ctx = mk_ctx(cfg, fuzz=fuzz_factor(c.id, c.reps) if fuzz else None)
    cur = card_state(c, cfg, today, now)
    return c, cfg, cur, cur.next_answers(ctx), today, max(next_day-now, 0), now, dr, decay

@patch
def answer_buttons(self:Collection, card, fuzz=True, now=None):
    "For each ease 1-4, `(next_state, delay_secs)` -- what a client shows on its answer buttons"
    _,_,_,ans,_,sur,_,_,_ = self._card_answers(card.id if isinstance(card,Card) else card, fuzz, now)
    return [(st, ivl_secs(ivl_days(st.ivl_kind(), sur))) for st in ans[1:]]

# %% ../nbs/04_scheduler.ipynb #a13556f3
@patch
def _leech_note(self:Collection, nid, now):
    tags = self.q1('select tags from notes where id=?', nid).split()
    if 'leech' not in tags:
        self.con.execute('update notes set tags=?, mod=?, usn=-1 where id=?', (f" {' '.join(tags+['leech'])} ", now, nid))

@patch
def _bump_deck_stats(self:Collection, did, today, new_delta, rev_delta, ms_delta):
    "Add an answer to the daily counters of deck `did` and its parents, resetting them on a new day"
    parts = self.q1('select name from decks where id=?', did).split('\x1f')
    names = ['\x1f'.join(parts[:i]) for i in range(1, len(parts)+1)]
    for did_,blob in self.q(f"select id, common from decks where name in ({','.join('?'*len(names))})", *names):
        c = decks_pb2.Deck.Common()
        c.ParseFromString(blob)
        if c.last_day_studied != today:
            c.new_studied,c.learning_studied,c.review_studied,c.milliseconds_studied = 0,0,0,0
            c.last_day_studied = today
        c.new_studied += new_delta
        c.review_studied += rev_delta
        c.milliseconds_studied += ms_delta
        self.con.execute('update decks set common=?, mtime_secs=?, usn=-1 where id=?', (c.SerializeToString(), int(time.time()), did_))

_GATHER_ORD = {1:0, 4:0, 3:1, 2:2, 0:3}  # queue -> gather order: intraday learn, interday learn, review, new

@patch
def _bury_siblings(self:Collection, c, cfg, now):
    "Bury (queue -2) siblings per the preset, only in queues gathered after the answered card's"
    g = _GATHER_ORD.get(c.queue, 99)
    qs = [q for q,want in [(0,cfg.bury_new), (2,cfg.bury_reviews and g<=2), (3,cfg.bury_interday_learning and g<=1)] if want]
    if qs: self.con.execute(f"update cards set queue=-2, mod=?, usn=-1 where nid=? and id!=? and queue in ({','.join('?'*len(qs))})",
        (now, c.nid, c.id, *qs))

# %% ../nbs/04_scheduler.ipynb #25b72dfe
def _shifted_d(mem):
    "FSRS difficulty normalized to the 0.1-1.1 range revlog factors use, x1000"
    return _round(((mem.difficulty-1)/9 + 0.1)*1000)

@patch
def answer_card(self:Collection, card, ease, taken_ms=0, fuzz=True, now=None):
    "Answer `card` (a `Card` or id) with `ease` (1=Again 2=Hard 3=Good 4=Easy), returning the updated `Card`"
    cid = card.id if isinstance(card,Card) else card
    assert ease in (1,2,3,4), f"ease must be 1-4, got {ease}"
    with self._tx():
        c,cfg,cur,ans,today,sur,now,dr,decay = self._card_answers(cid, fuzz, now)
        nxt = ans[ease]
        taken = min(taken_ms, cfg.cap_answer_time_to_secs*1000)
        mem = nxt.learn.mem if isinstance(nxt, RelearnSt) else nxt.mem
        d = _card_data(c)
        if isinstance(cur, NewSt): d['pos'] = cur.position
        d['lrt'] = now
        for k in ('s','d','dr'): d.pop(k, None)
        if mem is not None: d['s'],d['d'] = round(mem.stability, 4), round(mem.difficulty, 3)
        if dr is not None: d['dr'] = round(dr, 2)
        if decay is not None: d['decay'] = round(decay, 3)
        cols = dict(mod=now, usn=-1, reps=c.reps+1, data=json.dumps(d, separators=(',',':')))
        rl_fact = 0
        if isinstance(nxt, ReviewSt):
            cols.update(type=2, queue=2, ivl=nxt.ivl, due=today+nxt.ivl, factor=_round(nxt.ease*1000), lapses=nxt.lapses, left=0)
            rl_fact = _shifted_d(mem) if mem is not None else cols['factor']
        else:
            learn = nxt if isinstance(nxt, LearnSt) else nxt.learn
            if isinstance(nxt, LearnSt):
                cols.update(type=1, left=learn.remaining)
                rl_fact = _shifted_d(mem) if mem is not None else 0
            else:
                cols.update(type=3, left=learn.remaining, ivl=nxt.review.ivl, lapses=nxt.review.lapses, factor=_round(nxt.review.ease*1000))
                rl_fact = _shifted_d(mem) if mem is not None else cols['factor']
            iv = ivl_days(learn.ivl_kind(), sur)
            if iv<0: cols.update(queue=1, due=now+learn_fuzz(c.id+c.reps if fuzz else None, -iv))
            else: cols.update(queue=3, due=today+iv)
        rev = nxt.review if isinstance(nxt, RelearnSt) else nxt
        leeched = isinstance(rev, ReviewSt) and rev.leeched
        if leeched and cfg.leech_action==0: cols['queue'] = -1   # LEECH_ACTION_SUSPEND
        self.con.execute(f"update cards set {', '.join(f'{k}=?' for k in cols)} where id=?", (*cols.values(), cid))
        self.con.execute('insert into revlog values (?,?,?,?,?,?,?,?,?)', (ts_id(self.con,'revlog'), cid, -1,
            ease, ivl_days(nxt.ivl_kind(), sur), ivl_days(cur.ivl_kind(), sur), rl_fact, taken, cur.revlog_kind()))
        self._bump_deck_stats(c.did, today, int(c.queue==0), int(c.queue in (2,3)), taken)
        if leeched: self._leech_note(c.nid, now)
        self._bury_siblings(c, cfg, now)
        self._dirty()
    return Card(*self.q('select * from cards where id=?', cid)[0])

# %% ../nbs/04_scheduler.ipynb #12becb8a
@patch
def unbury_if_day_changed(self:Collection):
    "Restore buried cards once the day has rolled over since the last unbury"
    today,last = self.today(), self.conf('lastUnburied', 0)
    if last < today or today+7 < last:
        for cid,typ,due in self.q('select id, type, due from cards where queue in (-2,-3)'):
            q = {0:0, 2:2}.get(typ, 1 if due>1_000_000_000 else 3)
            self.con.execute('update cards set queue=? where id=?', (q, cid))
        self.con.execute("insert or replace into config values ('lastUnburied',-1,?,?)",
            (now_ms()//1000, json.dumps(today).encode()))

@patch
def _day_limits(self:Collection, did, today):
    "(new_left, review_left) for deck `did` today"
    cfg = self.deck_conf(did)
    cmn = decks_pb2.Deck.Common()
    cmn.ParseFromString(self.q1('select common from decks where id=?', did))
    new_done,rev_done = (cmn.new_studied,cmn.review_studied) if cmn.last_day_studied==today else (0,0)
    new_left,rev_left = max(cfg.new_per_day-new_done, 0), max(cfg.reviews_per_day-rev_done, 0)
    if not self.conf('newCardsIgnoreReviewLimit', False): new_left = min(new_left, rev_left)
    return new_left, rev_left

@patch
def next_card(self:Collection, deck=None, fuzz=True):
    "The next card to study in `deck` (default the whole collection, limits from 'Default'), or None"
    self.unbury_if_day_changed()
    today,now = self.today(), int(time.time())
    new_left,rev_left = self._day_limits(self.deck_id(deck) if deck else 1, today)
    cond,ps = self._find_sql(deck)
    def pick(extra, *xps):
        r = self.q(f'select c.* from cards c join notes n on c.nid=n.id where {cond} and {extra} order by c.due, c.id limit 1', *ps, *xps)
        return Card(*r[0]) if r else None
    c = pick('c.queue=1 and c.due<=?', now)
    if not c and rev_left: c = pick('c.queue=3 and c.due<=?', today)
    if not c and rev_left: c = pick('c.queue=2 and c.due<=?', today)
    if not c and new_left: c = pick('c.queue=0')
    if not c: c = pick('c.queue=1 and c.due<=?', now+self.conf('collapseTime',1200))
    return c
